### ISSUE TITLE
VCRUNTIME140D.dll missing

### ISSUE THREAD

**Issue by PiTM0N** [tremwil/CatalystNoclip#1]
EDIT: Sorry I did not notice this is no longer supported.

I assume I get this message, because it a Dev version. Can you share us a 'Release' build? Right now the tool does nothing :/ because it seemingly fails to inject the dll.
https://imgur.com/wDS3oHd

**Comment by tremwil** [comment]
Hi, 
I did know of the "Dev version" problem since quite some time, but was pretty sure I uploaded a fix. For current (and possibly further) troubleshooting, please open an issue on the page for the injected version of CatalystNoclip instead of here: [https://github.com/tremwil/CatalystNoclipInjected](https://github.com/tremwil/CatalystNoclipInjected).

**Comment by tremwil** [comment]
This project is no longer supported, but the injected one still is (although I don't have a lot of time to dedicate to it)

**Comment by PiTM0N** [comment]
I've filled in an issue form on the newer one, since that is the one I have issues with. Sorry for accidentally posting here and thank you for your time.
